call git add .gitignore
call git add status.bat
call git add add_em.bat
call git add notes.txt
call git add package.json
call git add config.js
call git add server.js
call git add serverless/index.html
call git add static/index.html
call git add src/App.jsx
